### ISSUE TITLE
Support docker

### ISSUE THREAD

**Issue by jiunbae** [naver/arcus#35]
Any plan for support dockerize arcus?

In [DockerHub](https://hub.docker.com/search/?q=arcus) seems  #to have many dockerfiles.

But repos are fragmented and some of theses are expired.

If you have any plan to support docker(or provide some guides for dockerize arcus)?

**Comment by jhpark816** [comment]
Have not made a plan, yet.
But, we need to support docker in someday.

**Comment by MaybeS** [comment]
I tried to make a simple file. 

This is a very simple attempt, but if you make a few more changes, will be able to set up the cache cloud and zookeeper automatically.

**Comment by minkikim89** [comment]
We don't have enough knowledge of docker.
So, we are not prepared to accept this pull request yet.

**Comment by namsic** [comment]
현재 [Docker Hub](https://hub.docker.com/search?q=jam2in)에서 arcus 사용에 필요한 docker image를 제공하고 있습니다.

해당 이미지를 활용한 클러스터 구성 예시는 [`docker-compose.yml`](https://github.com/naver/arcus/blob/master/docker-compose.yml) 파일을 참고 바랍니다.

---

[Docker Hub](https://hub.docker.com/search?q=jam2in) currently provides the docker image required to use arcus.

Please refer to the [`docker-compose.yml`](https://github.com/naver/arcus/blob/master/docker-compose.yml) file for an example of cluster configuration using this image.
