### ISSUE TITLE
Ubuntu 여러 환경에서 빌드가 가능하도록 가이드 / 빌드 파일의 개선이 필요합니다.

### ISSUE THREAD

**Issue by alekjin** [naver/arcus#45]
Clean 설치한 환경에서 Ubuntu 12.04, 16.04, 20.04까지 매뉴얼대로 빌드를 진행하였을때,

**Ubuntu 20.04.1**
libcppunit-dev 1.15에서 M4 Macro 삭제로 빌드가 불가능함.

**Ubuntu 18.04.5**
정상적으로 작동됨

**Ubuntu 12.04.5**
JDK 버전에 따라 상이한 빌드 에러를 냄
openjdk-6 : SSL Protocol Error
openjdk-7 : HOME_PATH에 관한 Error

JDK를 포함한 패키지의 버전에 따른 의존성 요소를 좀 더 안내하고 더 다양한 환경에서 빌드가 가능하도록 가이드가 필요함.

**Comment by LimChaeHoon** [comment]
libcppunit-dev 가 1.14 이상의 버전에서는 aclocal 의 cppunit.m4 가 removed 되었기 때문에, 아래 에러가 발생하게 됩니다.
configure.ac:37: error: possibly undefined macro: AM_PATH_CPPUNIT
따라서 "https://www.freedesktop.org/wiki/Software/cppunit/" 의 1.13.2 를 다운받아 빌드 후, cppunit.m4 를 aclocal 디렉토리로 복사해주면 이슈가 해결됩니다.

제 환경은 Ubuntu 18.04.5 였으며, libcppunit-dev 는 1.14.0-3 이었습니다.
aclocal 경로 경우 /usr/share/aclocal 이었습니다.

**Comment by jhpark816** [comment]
@SuhwanJang 확인 바랍니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
이번에 openjdk-6인 환경에서 build하였을 때, 마찬가지로 SSL Protocol Error 오류를 확인하였습니다.

**Comment by SuhwanJang** [comment]
m4 매크로 문제는 @LimChaeHoon 님이 제안하신 방법으로 해결하면 됩니다.
이에 대한 내용을

**Comment by SuhwanJang** [comment]
@alekjin 
본 이슈는 close 하겠습니다. 추가 문의가 있으시다면, 코멘트 주시기 바랍니다.
